project_id = "zhaxutljvjrlconjvuxp"

[functions.consent-management]
verify_jwt = false

[functions.generate-project-pricing]
verify_jwt = true

[functions.send-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false
