// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhaxutljvjrlconjvuxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYXh1dGxqdmpybGNvbmp2dXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTUxMjIsImV4cCI6MjA2OTU5MTEyMn0.rJH9czrd54MODNpZ7U8MAFjIunO6RcIHrSo283rxMuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});